### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by markfinger** [ixc/ixc-django-docker#14]
The glaring issues are in https://github.com/ixc/ixc-django-docker/blob/master/ixc_django_docker/bin/waitlock.py, which has a lot of code handling stdout/stderr that will need to be updated to properly handles bytes+str.

I took a 10 minute stab at it, but I ran into problems in the python-redis-lock package (locks could never be acquired). I hacked out a reimplementation of the lock acquisition with the `redis` package's builtin lock: https://github.com/andymccurdy/redis-py/blob/master/redis/lock.py, which seemed to fix the acquire and uncovered some more bytes/str errors, so I bailed and focused on other things.

**Comment by markfinger** [comment]
Note that these issues are preventing us from upgrading to Django 2+.

**Comment by Aramgutang** [comment]
I think we've fixed all the issues pertaining to this that have come up so far.

**Comment by Aramgutang** [comment]
It's working fine with Australian Museum. Are we also moving AGSA to py3?

**Comment by markfinger** [comment]
There's no pressing need, but it would be a good idea

**Comment by markfinger** [comment]
Everything looks good 

Thanks for the fixes, Aram :)
